### ISSUE TITLE
Move window

### ISSUE THREAD

**Issue by oldsaloon** [hovancik/stretchly#111]
It would be great if you could move the reminder window. Now it's fixed in the middle of the screen. You want to pause a video or close other things to take a break, but you can't because it's on top (especially if on a single monitor). So you just hit skip.

**Comment by hovancik** [comment]
Good point, I'll look into it.

**Comment by hovancik** [comment]
Hi, so right now it's not possible because I am using `focusable: false`to make stretchly work correctly. 

But I have added notifications that shows 30 seconds before break starts. I'll probably make release over weekend. 


![stretchly-notification](https://user-images.githubusercontent.com/4745859/30214806-fbce5f0a-94ad-11e7-93b4-dd8d2fb1ebb7.png)
