### ISSUE TITLE
[Feature request]: Customize Pause Behavior

### ISSUE THREAD

**Issue by nyx-haile** [hovancik/stretchly#1168]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### Problem description

I'd like to see the ability to customize stretchly's behavior during pauses. For some cases, it makes sense for the break timer to reset after the pause ends, but particularly in my case, (meetings, and games) I don't want to be interrupted during the pause but once it's over I'd like reminders to take a break before I dive back into my workday. 

### Possible solution

Ideally, a toggle or multiple choice between freezing the duration, continuing the timer until it hits zero, and resetting the break timer in the settings menu, or the advanced settings file.

### Alternative solutions

Alternatively, a single toggle for 'break immediately after pause' since for me and probably most people, I spend more than 15 minutes at a time in meetings or games and only really care about having the break immediately after the end.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the feedback :) 

So if I understand correctly, you would like to know when the pause is over? There used to be notification when pause has ended but people wanted it to be removed.

**Comment by BenediktAllendorf** [comment]
I'm just looking for a similar setting and I think it's not about the notification.

While in a meeting (especially with screensharing), I do not want to have any Stretchly breaks. I found a way to set my laptop into DND/Focus mode when a meeting is detected, and thus, Stretchly can react to that DND mode. But, Stretchly does not just pause breaks during DND, it resets them afterwards.

Let's say, I'm in the middle of a circle and my next long break would be in 15 minutes. Now, DND mode (start and end because I'm in a 5 Min call) is detected by Stretchly, which means my next pause will not be a a long pause in 10 minutes, but it starts again with a mini break in 20 minutes.

So, I do not want to be disturbed during a meeting, but I want my timers to keep ticking. The easiest would be to just skip breaks during DND, but even nicer would be to have breaks postponed until DND ends. (E.g., my next long break would be in 10 minutes, but I start a meeting which takes 30 minutes. After that meeting ends, I would like to get a long break, even though it's "out of schedule").

**Comment by BenediktAllendorf** [comment]
Here is a small PoC of what I've been thinking: https://github.com/hovancik/stretchly/compare/trunk...BenediktAllendorf:stretchly:MeetingDND

**Comment by hovancik** [comment]
Gotcha, I will start writing my thinking into new issue and close this one, so that discussion is at one place. There are related things that need to be taken into account. 

#1248
