### ISSUE TITLE
Multiple monitor suggestion

### ISSUE THREAD

**Issue by ErroneousBosch** [hovancik/stretchly#117]
Running on Gnome 3.24

Very nice app, but I wondered if there would be a way to have the window appear on all screens, not just one? Would make it harder to miss if I have mouse focus on one screen but am looking at another.

**Comment by hovancik** [comment]
I'll see into API how this could be done.

**Comment by sxmanton** [comment]
This is a feature I've been meaning to suggest as well.

**Comment by mathom01** [comment]
I've been wanting this too -- Stretchly can't really enforce breaks if it only blocks one window.

**Comment by tslin306** [comment]
Just started using stretchly and I think multi-display support is really necessary. 

P.s. I've used many eye rest reminder app and this is the best. Thank you all for the great work.

**Comment by hovancik** [comment]
Thanks! I need to make some bug fixes and then I hopefully can try to make this feature.

**Comment by tslin306** [comment]
@hovancik Great! Can't wait to see this feature in the future. You might want to check [this](https://github.com/electron/electron/blob/v0.36.10/docs/api/screen.md) out.

**Comment by altosaar** [comment]
+1, multiple desktops in Mac would be great–switching away means hiding the break notification.

**Comment by MrNoComment** [comment]
I keep cheating by looking at the second screen :/
This is mandatory 
Thanks

**Comment by ptitvert** [comment]
Yes at least have an option with a warning experimental code.
I was looking for alternatives, because I wanted to have the full screen message on all my screens.
The only one that was OK, was eyeleo, but he doesn't do full screen, so I can continue to work, even with the small message in the middle of the screen.

For me your project is the best. I will continue to use it, but I would very like to have a multi-monitor support, not only the main one.
