### ISSUE TITLE
Reset timer on resume from sleep

### ISSUE THREAD

**Issue by Quitch** [hovancik/stretchly#121]
Currently the first thing to happen when my PC resumes from sleep (S3) is that Stretchly tries to enforce a break. This also means the long break schedule is not correctly synced to when I was using my PC. I would suggest that Stretchly should simply reset its count to 0 when it detects a system resuming from sleep.

This is on Windows 10 x64 using version 0.9.0.

**Comment by hovancik** [comment]
I've added it, but AFAIK it's very buggy with electron (since 2015), so not much to do here until they fix it.

**Comment by sxmanton** [comment]
One thought is that instead of using power monitoring to accomplish this, we could add some sort of check to the timers. Basically have scheduler wrap the function which gets called by the timeout with a check, so that if it is already a certain number of minutes past when the timeout was supposed to trigger (i.e. timeleft() < -X) then it resets itself, or emits some event which breaksPlanner can use to properly reset things.
