### ISSUE TITLE
[Feature request]: show pre-break warning

### ISSUE THREAD

**Issue by AlexMKX** [hovancik/stretchly#1217]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Problem description

When using stretchly, I notice that I'm getting professional and fast in breaks postponing and skipping.
Prior to Stretchly I've been using Workrave. By analysing my behavior I noticed, that user not always able to synchronize his breaks with stretchly scheduler.  Sometime (often) stretchly pops up when I'm typing, or when I'm in the middle of something very important. In this case I'm postponing breaks.
Workrave has ability to warn user that break is coming, so he can finish his work slack or pospone slack in favor of health.

### Possible solution

Add the functionality of non-intrusive warning that break is coming. Either with non-disturbing auto-closing popup or with tray countdown timer (like Workrave do).

### Alternative solutions

Have no ideas :(

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, there is a system notification 10 seconds before Mini and 30 seconds before Long break. You can configure that : https://github.com/hovancik/stretchly#editing-break-notification-interval- 

You can also customize the postponement behavior: https://github.com/hovancik/stretchly#editing-postpone-functionality-

**Comment by MaticSulc** [comment]
Hi @hovancik,
I've got breakNotification and microbreakNotification turned off, but I still get those system notifications.
Is there a way to turn them off completely? 
Thanks in advance.

**Comment by hovancik** [comment]
Could you please screenshot what you mean?

**Comment by wolftune** [comment]
I find the system-notification not intrusive enough for some situations. WorkRave is *really* bold. It has its own small box that cannot be dismissed, and if the cursor moves to it, it moves to another spot on the screen so that it never blocks where you need to see. It gets a bit more naggy if you keep working but actually doesn't force-start full break. Instead, the break starts after a few seconds of no input activity.

So, this is really a remarkable balance. Bold-enough and naggy-enough prompt, but I still have to stop working for the break to go ahead. However, WorkRave has a setting for how long it will let you postpone the break before it *does* force it.

That one aspect of WorkRave is really superior for me, though I prefer everything *else* about Stretchly. I suggest trying WorkRave so you can see its approach.

One important use-case: I'm choosing a tool for kid's computer. I'm concerned about frustration if kid is playing a game and gets suddenly interrupted. The system notification warning should be enough to hit pause but not necessarily. With WorkRave, if he keeps playing, it will get more naggy and then give up and postpone and do it again after a set time, and if he skips the prompt too many times, it will force the break anyway. With Stretchly, it's just hope-he-sees-the-system-notification-and-pauses, otherwise, it will be an upsetting experience which is not the goal.

**Comment by hovancik** [comment]
> With WorkRave, if he keeps playing, it will get more naggy and then give up and postpone and do it again after a set time, and if he skips the prompt too many times, it will force the break anyway. 

you can also make more postpones with Stretchly https://github.com/hovancik/stretchly#editing-postpone-functionality- 

I prefer not to make custom notifications, as with electron, positioning windows is basically painful and I value my mental health

**Comment by unixerius** [comment]
I reckon you can close this issue ticket @hovancik. The feature they were asking for is in the product. 

By the way, you rock! :)
