### ISSUE TITLE
Instead of the notification, show a floating warning right before the break starts, skipping the break if the user doesn't stop the activity. (An alternative to fading in the break window)

### ISSUE THREAD

**Issue by decadent** [hovancik/stretchly#144]
This is a shameless rip-off from a feature in Workrave. Other popular apps behave similarly by fading in the break window gradually, but Workrave's solution is better from the usability standpoint.

When a break is due, the app shows a floating window away from the mouse pointer, ticking down a timer of about 30 seconds to the proper start of the break. This allows the user to finish whatever micro-task they are doing at the time, such as writing a sentence—without the app stealing away the focus in the middle of an activity.

However, if the user does not stop moving the mouse or pressing keys, the window just disappears when the timer runs out, and the break is skipped, or postponed in case of a normal break. This lets the user continue doing an urgent task and saves a click/keypress to skip the break.

An illustration:

![Workrave screenshot](https://i.imgur.com/IoGi1Yf.jpg)

<br/>

Additionally, Workrave counts the warning time in the break time, at least with normal breaks—or probably counts just the time of inactivity. This should be implemented if possible, but not necessarily.

Currently Stretchly lacks the functionality of postponing a break—for this issue we'd need only basic internal implementation, without prominent changes in the UI.

I'm definitely coding this for myself but Jan might want to decide whether the main release needs this feature.

**Comment by hovancik** [comment]
Well, we could do that as alternative to the notification, but personally, I like the notification more. It's because stretchly works better for me when it's more aggressive. 

Right now I am working on natural breaks, see #140 . 

What we can do is let the user decide what he wants before break: 
- show notification 30 seconds before
- check for inactivity as you said and skip if not inactive
- nothing

I don't like the idea of postponing, because that's what I would do all the time, then ;/ And I don't want stretchly to be copy of other products ;] 

What I plan to do instead is to count number of skipped breaks and then don't let user skip breaks anymore.

**Comment by hovancik** [comment]
There is no plan to change the current behavior, so closing.
