### ISSUE TITLE
[Feature request]: Reading calendars. when in meeting it should not be appearing 

### ISSUE THREAD

**Issue by PrismWatch** [hovancik/stretchly#1507]
### Version

- [X] I'm using version 1.16

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 23H2

### Problem description

I'm always frustrated when a pause comes and I have a meeting. This isn't very pleasant.

### Possible solution

It would be lovely if it could read calendars in the settings options. for example: Outlook Calendar and Google Calendar, so it does not pop up when I am in a meeting.

### Alternative solutions

Maybe 
- add a time frame to your settings when the app cannot break. So I can add my meetings to it.
- or a pause button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the feedback. 

I don't have experience with connecting to calendars, and many people use many different calendars so that would be endless task. Unfortunately, I don't have skills or time for that, so I wont be working on that. Sorry about that. 

Ideally, there is an app that can set Do Not Disturb/Focus mode when user is in a meeting, which Stretchly follows, so breaks would get paused.
