### ISSUE TITLE
Idle time

### ISSUE THREAD

**Issue by jt007** [hovancik/stretchly#152]
Great software! Here is an idea for some improvements.
I have noticed that your new version 12.0 reset the microbreak timer if I have a natural break from the computer of 5+ minutes. That's a great feature, but I have a suggestion for some improvements.
If I am out of office for less than 5 minutes, the microbreak may in this version start just a few seconds after I start using my computer. That’s a bit frustrating. In this case I have already had a microbreak (more than 20 sek break), so the microbreak timer should have been reset.
When reading on the computer, it sometimes may be no mouse movements for 1-2 minutes, so to make sure it actually has been a real natural break, it should require an idle time for 2 minutes to reset the microbreak timer. That’s my suggestion. What do you think?

**Comment by hovancik** [comment]
Let's hear what other people think. I am open to the idea changing from 5 to 2 minutes... Not really sure if 2 or 5 is better... Or maybe have 5 min default and let user configure it.

**Comment by jt007** [comment]
Thanks for your reply:)
I use the option “don’t let me skip microbreaks”, (I need it:)), so therefore it’s a bit frustrating to be forced to take another break just the moment I return to office after a break of up to 5 minutes.  
When I just return from the bathroom etc, I don’t need a 20 seconds break :)
Your proposal of letting users configure it would solve the problem:)

**Comment by xim** [comment]
I'm for more configurability of idle time perception. A couple of descriptive configuration fields (e.g. pause timers after [2] minutes inactivity, reset microbreak timer after [5] minutes inactivity, reset normal break timer after [15] minutes inactivity) also automatically tells the user exactly how the "monitor system idle time for natural breaks" works.

**Comment by kostadinnm** [comment]
Hi there!
Kudos for the great app!
I'd like to add a suggestion for the idling monitor - could we have some kind of monitoring the system usage(say the cpu usage) in order to have more accuracy on whether a user is sitting in front. Another thing will be whether the image on the monitor is changing.
While typing this, I realize that the best thing would be having a dedicated sensor(and an accompanying api) like this on some samsung smartphones:
![smartstay](https://user-images.githubusercontent.com/18436405/36390554-2655cdd8-15ac-11e8-8bc5-5154907ed908.jpg)
Anyways, I guess a dummy implementation using the resources could work for some of us(e.g. my little cousin watching youtube) for a while.
Cheers,
Kostadin

**Comment by lundibundi** [comment]
@hovancik what about stopping timer after [1] (configurable) min of inactivity and then upon user return if idleTime is bigger than the duration of a next break (break or microbreak) then skipping it, otherwise adding idleTime to the timer so that break happens later? This will most likely always skip microbreaks (as they are short) upon such pause but I think that's the desired behavior.

**Comment by p-himik** [comment]
I switched from Workrave to Stretchly and would absolutely love to see the idleness detection being configurable either via the UI or via the config file.

**Comment by dyipon** [comment]
Please add support to "idle detection sleep" support sleep/poweroff.  Now if I sleep the computer for 20 minutes, after wakeup I get a microbreak immediately. Thanks

**Comment by hovancik** [comment]
@dyipon  what OS are you on? this works for me in windows/mac last time I checked

**Comment by dyipon** [comment]
up-to-date Windows 10.

**Comment by hovancik** [comment]
Well, I guess they changed something again... Will have to look

**Comment by joydashy** [comment]
Is there any way to have the natural break be the same length as the long break? I have it set to 3mins every 20mins. If I have a 4min natural break, then come back, it will tell me to have another 3 mins break after all...even though I just had a longer break than I need!

**Comment by hovancik** [comment]
@joydashy natural break is taken into consideration if it is longer then length of break (not microbreaks).

I guess your "3mins every 20mins" is microbreak?

**Comment by joydashy** [comment]
@hovancik I have set 10 sec every 10mins micro. If I set 3 mins every 2 micros as normal break, then a natural break of 3mins should be taken into consideration? That's what I would expect, but not what I saw happening. But if you say it works like that, will test again!

**Comment by hovancik** [comment]
@joydashy unless there is some bug, it should be that way

```
        if (lastIdleTime > this.settings.get('breakDuration')) {
          this.emit('naturalBreakFinished', idleTime)
        }
```
I check if idle time after user coming back is longer then break duration and then reset breaks

**Comment by hovancik** [comment]
There is no plan to change the current behavior so closing.

**Comment by Chealer** [comment]
This is visibly related to issue #1560.
