### ISSUE TITLE
Snooze button

### ISSUE THREAD

**Issue by radu-gheorghe** [hovancik/stretchly#161]
First of all, thanks a lot for doing Stretchly, the health industry should be grateful :)

Snooze is the feature I miss most from Workrave: 30s is usually too short of a notice for me to wrap up before taking a break (or maybe that can be made configurable?). Then when the break comes, I need to skip it and when I do, I forget about it.

If I could postpone the break for 5 minutes or so (configurable?), that would be awesome.

**Comment by hovancik** [comment]
Hi, you can configure the reminder time by editing the config file: 
https://github.com/hovancik/stretchly#editing-breakmicrobreak-notification-interval 

The reason why it's not configurable is to make stretchly easy to understand. Settings are kept as small as possible (and are opinionated ) with option to edit them by hand in config file. 

About postponing: for me, I prefer not to have postponing feature, because then I would never take a break ;] I want stretchly to force me into break. But I will think about it

**Comment by radu-gheorghe** [comment]
Thanks! I didn't know of the configuration file. I've edited that out to two minutes, hopefully that gives me time to wrap up and actually take a break :) For now, stretchly only really serves as a reminder to take breaks every now and then, I don't truly respect them. I think that if I had a postpone button, even if I'd use it repeatedly, it would be better than to skip breaks entirely (which is what I do now).

**Comment by hovancik** [comment]
That makes sense. I can image having possibility to postpone break once.

**Comment by hovancik** [comment]
@BullHorn7 you can pause the breaks and restart them when you are ready from tray menu
