### ISSUE TITLE
Error on npm start on 64-bit Windows 10 machine

### ISSUE THREAD

**Issue by Rahmeen14** [hovancik/stretchly#197]
I followed the steps on the readme, i.e., cloned the repo, followed by ```npm install```. On ```npm start``` the following error occurs:
```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\hp\AppData\Roaming\npm-cache\_logs\2018-02-03T13_14_11_398Z-debug.log
```
How can I resolve it?
I can provide the logs if that should be necessary.

**Comment by hovancik** [comment]
Maybe you run that from ./app directory? You should run it from root directory. 
eg. 

```
cd stretchly
npm start
```

**Comment by Rahmeen14** [comment]
![screenshot 66](https://user-images.githubusercontent.com/24973238/35769781-65305244-0936-11e8-92f0-67c9b5683b1e.png)


This is the error. If you could please help me out?
Thank you for your time ! :)

**Comment by Anisha1234** [comment]
@Rahmeen14 what is your node version?

**Comment by Rahmeen14** [comment]
@Anisha1234 thank you for the help!
I upgraded my nodejs to v8.9.4. Did try the step-wise solution this link has to offer, the same error persists.
Is there anything else you have in mind?

**Comment by hovancik** [comment]
node version that I use is specified in `package.json `as 
```
  "engines": {
    "node": "7.9.0"
},
```

For WIndows, I remember I had to install some windows c libraries, but I don't remember what it was.

**Comment by Akshitaag** [comment]
@Rahmeen14  This took a lot of time but it finally worked.

Follow these steps:
1. In windows power shell , type `Start-Process powershell -Verb runAs`.This runs power shell as an adminstrator.
2. In the administrator power shell , type -
`npm --add-python-to-path='true' --debug install --global windows-build-tools`
This might take a long time.
3.Now cd into stretchly and `npm install`.
4. After that, type  `npm start`.During npm start , it asks to reinstall electron:
Type this:
`npm install electron --verbose`
5. `npm start` again.

The above steps worked for me. Hope it works for you too.

**Comment by Rahmeen14** [comment]
Yes it helped! Thankyou!

**Comment by kostadinnm** [comment]
I wanted to use `yarn` instead of `npm`. If anyone's interested, here are the commands I needed to execute:
In an elevated shell:
`yarn global add windows-build-tools --add-python-to-path='true' --verbose`

Then, when I ran `yarn install` to build the app, I got an error about missing `electron-builder`(cannot list the concrete error because it seems to have depleted both the shell screen max line-length and the yarn error log file size). So I added it globally:
`yarn global add electron-builder --verbose`. The `--verbose`-switches are not mandatory.
The last one may be a yarn bug, because the package `electron-builder` is in the `package.json` and should've been downloaded automagically.

What's interesting is that if I run `yarn check` to check the integrity, it somehow reads the `package-lock.json` from the source and displays some warnings:
```
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-linux@1.7.2: The platform "win32" is incompatible with this module.
info "app-builder-bin-linux@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.7.2: The platform "win32" is incompatible with this module.
info "app-builder-bin-mac@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-linux@1.6.0: The platform "win32" is incompatible with this module.
info "app-builder-bin-linux@1.6.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.6.0: The platform "win32" is incompatible with this module.
info "app-builder-bin-mac@1.6.0" is an optional dependency and failed compatibility check. Excluding it from installation.
```
I am overwhelmed by the tons of stuff these things need to get going, but I guess if/when `electrino` migration happens it'd be mostly on the lightweight side :)

I'll try running stretchly tomorrow.

Cheers,
Kostadin
