### ISSUE TITLE
Silence break start notification sound

### ISSUE THREAD

**Issue by AndyDeNike** [hovancik/stretchly#201]
I often listen to high volume music with headphones and the initial break start notification sound hurts my ears sometimes; allowing user to silence this would be much appreciated.  Great application, keep up the great work!

**Comment by purva98** [comment]
Hey @AndyDeNike!
The problem is very geuine, and strechly provided a solution to it :)
In the audio scheme section, different sound profiles are offered, one is "silence"
![audio_scheme](https://user-images.githubusercontent.com/24644158/36135787-4189d5fc-10b3-11e8-8bf8-c408e921fc99.jpg)
I hope this helps!! cheers!

**Comment by AndyDeNike** [comment]
wow, helps so much, just realized it was the default Macbook notification sound.  Thanks for clarity!
