### ISSUE TITLE
Pause until tomorrow

### ISSUE THREAD

**Issue by nfelger** [hovancik/stretchly#243]
This is a feature suggestion.

I like using Stretchly all when I'm working, but I use the same laptop for work and leisure and I often find myself in a position where I'm watching videos or doing other things with my laptop in the evening. In those situations, I don't always like having the breaks.

What would be nice for that is a menu option to pause Stretchly until the next morning (e.g. 6am local time), similar to the "Disable until sunrise" feature in f.lux (https://justgetflux.com/).

What do you think about this?

**Comment by hovancik** [comment]
I like it ;]  
The only question is what would "tomorrow" mean.  I guess 6am could be ok

**Comment by lundibundi** [comment]
I'll work on it. I think I'll implement 2 versions
* manual hour specification
* specification of coordinates so we will be able to calculate the actual sunrise
@hovancik what do you think?

**Comment by lundibundi** [comment]
Oh, that's good, but imo it's easier to just push `until morning` than to manually specify time (if I understand correctly how custom pause will work) because that's much more common use case, for example when I'm finished with work for today and want to watch films etc.

Location thing is completely optional and available only through manual edit of 'config.json' so this shouldn't be that big of a deal, even more so this only needs approximate location so city or even country will work just fine.
