### ISSUE TITLE
Lock all npm dependencies to exact versions instead of auto-update

### ISSUE THREAD

**Issue by aleuca** [hovancik/stretchly#267]
Currently all dependencies are on auto-update. We should lock in the exact versions to avoid breaks in the future when dependencies come out with new versions. From now on when we run `npm i dependency_name --save --save-exact` to always lock in the current version.

**Comment by hovancik** [comment]
I guess this is good solution. If anyone is more familiar with nodejs let us know ;]

**Comment by lundibundi** [comment]
from here:https://github.com/hovancik/stretchly/commit/3dc28c5fa658a49efe84aae6b64fef5299701288#r29659128
But that's what [semver](https://semver.org/) is for. "^version" stands for "any compatible with 'version'" therefore it is usually safe to update. Yeah it is still possible that the app breaks but it's rare and usually unintentional, developers will most likely quickly fix any breakage in the upcoming, also compatible version when reported.
And this usually won't happen on master because in order to actually get those updates you have to `npm update` (`npm install` may also use new versions but this also have to be PR into the repository as both `package.json` and `package-lock.json` will change) and then PR new versions, so it is kind of pointless to have exact versions in `package.json` (it may be useful only in some corner cases where you know that you don't need to update, or developer doesn't respect the semver).
Also we have `package-lock.json` in the repo, therefore if you `npm install --no-save` npm **will not** update any packages and install exactly what is in `package-lock.json` even if `package.json` has "^ver" in it. (package-lock saves the exact whole current dependency tree, so every dependency and dependency of dependencies and so on is fixed).
Anyway this is much better that having to manually update everything, because not only you won't get new features, but also any bugfixes will have to be monitored manually in all libraries used. This way we will only need to 
* run `npm update` and check that everything works to get all compatible features and bugfixes
* manually `npm update app@version` major versions, which may by definition be incompatible as some breaking changes were introduced (npm will not update those without manual update with version specifier if you have "^ver" set in dependencies).

So I suggest we revert that change as this will make maintenance of dependencies much harder, with having manually check for new versions and look for them, instead of just getting them 'almost' for free with semver.

**Comment by aleuca** [comment]
@lundibundi This is a good find, thanks! @hovancik shall we revert back to auto-update? This is probably best, but then we just need to keep in mind that `package-lock.json` will be changing with updating dependencies.

**Comment by aleuca** [comment]
@lundibundi good find, thanks! @hovancik should we revert back? We can just use the `--no-save` tag instead of the `--save-exact` to maintain the `package-lock.json` the same.
