### ISSUE TITLE
definition of breaks

### ISSUE THREAD

**Issue by pjebs** [hovancik/stretchly#270]
I was wondering what the difference was between a break and a microbreak?
Is it only the duration( one is meant to be shorter).

What is a natural break? how does it relate to idle time? what is idle time?

**Comment by hovancik** [comment]
Hi and thanks for questions ;] 

**Microbreak** is meant to be small break, little exercise to remember to keep your body in check. So small eye or posture exercise, remember to drink or so. 

For me personally it's about getting my mind to think about my posture, to remember to close my eyes and breath. 

**Break** is meant to be longer break after few microbreaks. It allows you to make a longer exercise, to keep your mind fresh and so on. 

For me personally it's about letting my mind relax and take some time off the computer. My brain can then figure out solutions to problem I am solving by itself. 

**Natural break** is when you leave your computer (not because of break or microbreak). We say that natural break occurs when you leave your computer for longer than 5 minutes. (This is what idle time means - when your mouse/keyboard is idle). When you leave your computer for let's say 10 minutes, we say that you took natural break and after you come back we reset the timers. 

(note: idle time detection is not that good, so it does not always work 100% on all platforms)

**Comment by pjebs** [comment]
thanks
