### ISSUE TITLE
Download checksums

### ISSUE THREAD

**Issue by douglasg14b** [hovancik/stretchly#283]
### Description

Provide MD5 (or other) checksums for downloads to prove the downloaded files are what should have been retrieved from the download source.

It's not uncommon for attacks to occur that modify miscellaneous software downloads to inject malware these days (ie. through a compromised host). Having a checksum of what the file(s) should be is a good way to validate against this. And is just good social hygiene for software.

**Comment by hovancik** [comment]
Agreed. Will do with next release.

**Comment by hovancik** [comment]
Hey, just checkind and files like latest-mac.yml have checksums inside ;]

**Comment by qzweng** [comment]
Hi, many thanks for the great software! I am a heavy user and do love it.

**Any 3rd-party download link available?**
One annoying problem is that the downloading of the latest version is quite slow. It took me over 9 hours to download and usually failed in the middle. I guess it might due to its popularity that makes the service provider limit the access. Maybe posting a third party archive, like https://mac.softpedia.com/get/Utilities/stretchly.shtml, will help, but I'm not sure whether this mirror is authentic.

**Any checksum available?**
That's why I reopened this issue. The `latest-mac.yml` seems no longer exists in the repository. Could you help post the checksum in the download page? Since the "Stretchly is not signed", this information will be a comfort for 3rd-party downloaders.

Thanks again for the great piece of work.

**Comment by hovancik** [comment]
Hi @qzweng , checksums are located on release pages, ie https://github.com/hovancik/stretchly/releases/tag/v1.2.0

**Comment by qzweng** [comment]
Thanks for the reply! I guess you mean the ".blockmap"? Given a "dmg" file, could you provide a hint about how to check this authentication with ".blockmap" file?

I have googled it, found some discussion about "blockmap" (e.g.,  https://github.com/electron-userland/electron-builder/issues/2851), but still cannot work it out. Thanks!

**Comment by hovancik** [comment]
Hey no worries :) glad you found it :)
