### ISSUE TITLE
Feature request: pausing strechly when certain programs are running

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#389]
### Prerequisites

- [x]  I'm using latest version: v0.19.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

I would like to add a settings feature that will allow user to select a list of programs that, when opened, will trigger a pause mode in strechly. That will make it more convenient to use strechly while using programs where interruptions are inconvenient (e.g. certain games). Please let me know if it's something I can work on. Thanks!

**Comment by hovancik** [comment]
Did you find some library that can do that? I was looking for one but didn't find one.

**Comment by vlezzhov** [comment]
I believe this could work for checking if a process is running: https://www.npmjs.com/package/ps-node

**Comment by hovancik** [comment]
Looks promising! How would you do in terms  UX and functionality?

**Comment by vlezzhov** [comment]
I'm thinking the user should just be able to go to settings, choose apps that will be on the list of exclusions, and the program will be in pause mode when the process for that program is running, and will resume when the process stops. The menu will have a separate page for that feature, with a list of current apps. Next to each element of the list will be a delete button (red X). And there'll be an element for looking up/adding programs. Maybe that page should have a brief description of the function for the user.

**Comment by vlezzhov** [comment]
This all sounds good. I can go ahead and work on it soon, when I have more time (exam week coming up :) )

**Comment by Luukgr** [comment]
@vlezzhov Already progress with this? (maybe I can try to find some time as well)

**Comment by AnRetset** [comment]
Hi, checking in regarding the current status of this feature request?  Would be lovely to have Stretchly automatically be disabled when blacklisted applications are in focus.  I also think having an option to "disable for fullscreen applications by default" would be great.

**Comment by hovancik** [comment]
Hi @AnRetset , no progress on my side, I am working on app redesign.

**Comment by hovancik** [comment]
I've hacked around a PR with this function, feel free to try.

**Comment by decadent** [comment]
Personally I find it more useful to pause Stretchly when a certain app is in foreground (movie player, a game, etc). Sometimes I pause the movie or the game and switch to other apps, and in my config Stretchly continues the break reminders in this case. I even think it might be possible to get the topmost app in Electron—I seem to have done that in a project, though at present time I've implemented this via an external app (Hammerspoon, which handles app switches as events instead of polling).

However, I quickly ran into a couple further feature wishes for this workflow of mine:

- If I switch to the player and soon back (perhaps taking a look at a short clip), the breaks are started anew. I'll probably add a delay before the breaks are paused, in the Hammerspoon script.

- If I spend twenty minutes with a movie or a game, Stretchly then goes on for another thirty before the big break. This one is a bit trickier: preferably Stretchly would start a long break in ten minutes from when it's unpaused (in this example), with microbreaks along the way. I might add a command-line command “run a long break in X minutes”—then in code, regular breaks would be a specific case of that, with X = config time for long breaks. This would also take care of the first wish above.

With some whacking around in Firefox plugins, I might also be able to implement pausing for Youtube videos. Basically, I think Stretchly works better as a self-contained app in this configuration, with other integration glue pausing/unpausing the breaks from outside.

**Comment by hovancik** [comment]
> Basically, I think Stretchly works better as a self-contained app in this configuration, with other integration glue pausing/unpausing the breaks from outside.

Yea I agree. For example, let's say on MacOS, Teams should set system-wide DND mode and then Stretchly just follows that. Because apps such as Teams/Zoom/whatever should use what MacOS prepared for them. There's no way I would be implement different behaviours of Stretchly per different apps and per different state of the other app. I can get that they run but that's it.

With regard to pausing/resuming: right now everything is simply reset on resume. I wanna add some kind of state, but I am afraid of this, as most of the code would need to be refactored. And I can see argument for both:
- when I return from ie suspend, sure, I wanna reset all breaks and start from new
- when I return from ie suspend, sure, I wanna continue where I left of so give me Long Break in 3 minutes. 

Making this configurable would further complicate everything.

**Comment by decadent** [comment]
> With regard to pausing/resuming: right now everything is simply reset on resume. I wanna add some kind of state, but I am afraid of this, as most of the code would need to be refactored

For myself, I envisioned this as again being driven by external integration apps which would count how long I spent with the game/movie—thus Stretchly wouldn't need to keep this value. However come to think of it, the previous un-paused duration should be included, and the whole comes down to ‘time since the last break’, so there might be sense in doing it in Stretchly.

As for the code, I was thinking of simply doing ‘extract a function’ and creating ‘scheduleABreakInXMinutes’, so that the code scheduling regular breaks would call it with the value for normal break interval, and external apps with whatever they want.

In fact, my persistent itch is that I see Stretchly as a perfect embodiment of finite state machines—specifically the internal logic of ‘break/work/pause’ is an FSM, and everything else is isolated mechanisms calling into the FSM or watching its states, possibly even also FSMs of their own. Making the states and transitions explicit would make the code more robust, and having the table of transitions would make it obvious for any new mechanism which transitions it needs to handle. (I, uh, have some little history with bugs in this kind of code, and in general main.js-style code tends to get hairy.) I keep meaning to draw up a plan of which states and transitions would there need to be and to think of how new ones could then be added in the future.

**Comment by hovancik** [comment]
Yeah, I think I agree with FSM part. I never really thought about it as FSM but I am kinda doing something similar. There is a BreakPlanner which interacts with other parts like DND, Idle Time etc via Events.

**Comment by hovancik** [comment]
I plan also to improve outside-world interaction with Stretchly by adding some sort of communication via sockets or something. CLI right now is hacky a bit and not really flexible.

**Comment by e-t-l** [comment]
Is the blacklist/exclusions feature included in v1.7.0? #886 looked like it had been merged but I don't know if that all went into the most recent release build. I don't see any preferences for it in the app.

**Comment by hovancik** [comment]
@e-t-l yes, it is there, configurable via preferences file 

https://github.com/hovancik/stretchly#advanced-preferences
https://github.com/hovancik/stretchly#pauseresume-breaks-only-when-specific-command-is-running

**Comment by e-t-l** [comment]
Thanks, I see now. Didn't realize it wasn't part of the GUI. ~~On Windows, I'm guessing we would put the full path to the executable? (e.g. Skype would be "C:\Program Files\WindowsApps\Microsoft.SkypeApp_15.68.96.0_x86__kzf8qxf38zg5c\Skype\Skype.exe") ...And as I type that, I see a potential issue. Windows apps change around the package name, and therefore the directory name, with every version. Any chance the Exclusions feature could support wildcards?~~ I'm silly. putting the full pathnames caused an error, while putting just the executable name worked as expected when I tested it.

**Comment by hovancik** [comment]
Yeah, I am checking for substring, so if "Skype" is running as an app, "ype" would work. But it is case sensitive, so "YPE" would not. Best way to check in some sort of task manager or however it is called.

**Comment by r3a1d3a1** [comment]
Hi Jan & Thanks for the great app!
I was trying this new feature, but it seemed amiss to me.
I whitelisted an app so as to override DND by editing the preferences file as follows:
```
"appExclusions": [
    {
        "rule": "resume",
        "active": true,
        "commands": [
            "studio"
        ]
    }
]    
```  
However, Stretchly still remains paused during DND while the app is up. Matter of fact, it mentions that it's paused due to an app exclusion! (So, the problem doesn't lie with the detection of the app.)

I took a look at the code and https://github.com/hovancik/stretchly/blob/trunk/app/breaksPlanner.js#L75 seemed suspicious to me, as I believe it should've been `if (this.isPaused` instead of `if (!this.isPaused`. 

Can you please check?

**Comment by hovancik** [comment]
Hi @r3a1d3a1 , I believe the error is in the message. It should be "Paused - DND is on". 

There are different things that can pause/unpause breaks (and there are different ways what happens, even though I use only one word "pause"). Therefore I kinds had to pick sort of hierarchy. But as DND comes from OS, it is more important than appExclusion. Another example is that when DND is on, user can't Pause/Reset/Resume as DND is more important.

**Comment by r3a1d3a1** [comment]
I see. So such whitelisting is only meant to override none-DND pauses...
I wish it had the option of overriding DND as well.
Thanks anyways!
