### ISSUE TITLE
Tray tooltip won't show in XFCE Manjaro

### ISSUE THREAD

**Issue by sispus** [hovancik/stretchly#438]
### Prerequisites

- [ x] I'm using latest version: v 0.20.1 
- [x ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]
Tray tooltip stops working. It was shown before.

Operating system: Manjaro Linux XFCE

### Steps to Reproduce

1. Hover on the tray icon
2. Tray tooltip won't appear.

**Expected behavior:** 
Tray tooltip to appear

**Actual behavior:** 
nothing

**Reproduces how often:** 
every time

**Comment by hovancik** [comment]
Hi @sispus, this is unfortunately a known issue in electron: https://github.com/electron/electron/issues/15161 

It was working in version 2 of electron, but that version is not supported as we are now in electron v5. 

I've reported this issue in October 2018 but nothing happened, and I honestly does not expect anything to happen. Similar issue is on mac, actually since I created stretchly few years ago and it was not fixed. I am thus looking for designer to do stretchly in another way as I can't keep running version 2 of electron: https://github.com/hovancik/stretchly/issues/421
