### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by angelhdz** [hovancik/stretchly#463]
- [ ] Custom colors
- [ ] Custom background image for each break, or one for all
- [ ] Custom times
- [ ] Sound at the beginning, not at the end (or setting both?)
- [ ] Background music or sound fx while the break lasts, for example some water flowing, beach waves, forest with animals sounds, rain, relaxing instrumental music.
- [ ] Window Transparency
- [ ] Custom Text/Messages
- [ ] Insert at 1 image at the bottom, related to what the message says. If it says "Go, grab a glass of water" then image of a water bottle, a river or  waterfalls, or glass of water with ice. If it says "Go, grab a cup of coffee", the image can be coffee grains, coffee with heart, ora person drinking coffee.
- [ ] Custom Pause times
- [ ] Choose from an Analog clock animation or a  progress bar, and if progress bar, customizing the accent color.
- [ ] "...nah, I'll just keep going" should be a material button, with customizable text, with a default of "Skip" or "Skip Break"
- [ ] A "Pause" button at the side of the skip break button, clicking it will show the Pause times context menu.
- [ ] Settings page needs improvement. Layout, and material animated toggle button instead of checkbox.
- [ ] Why are the texts lower case!?
- [ ] Any reason why the logo in the tray is monochrome by default?
- [ ] Skip break with a keyboard shortcut

- [ ] Language settings. The app's text can be modified in a JSON file.

I am developer, I can build my own app, but decided to try this one to support other developers' projects, but there are so many missing expected features. 

Cheers

**Comment by hovancik** [comment]
Hi and thanks for the ideas ;] A lot of things can be done via editing advanced settings file: https://github.com/hovancik/stretchly#advanced-settings. Basically every setting is in that file, thus can be changed there.

`Custom colors` - in settings file 

`Custom background image for each break, or one for all` - I want the app to look very simple, thus I don't plan to have images for breaks

`Custom times` - what specifically do you mean? You can edit interval and how long the breaks are

`Sound at the beginning, not at the end (or setting both?)` in settings file

`Background music or sound fx while the break lasts, for example some water flowing, beach waves, forest with animals sounds, rain, relaxing instrumental music.` - I don't plan to do that in foreseeable future to keep app small

`Window Transparency` this could be done I guess, not sure how would that look. 

`Custom Text/Messages` in settings file

`Insert at 1 image at the bottom, related to what the message says. If it says "Go, grab a glass of water" then image of a water bottle, a river or waterfalls, or glass of water with ice. If it says "Go, grab a cup of coffee", the image can be coffee grains, coffee with heart, ora person drinking coffee.` as I said previously, I don't plan to add pictures

`Custom Pause times` - this could be done, but I prefer to have little code as possible so I don't plan to add that

`Choose from an Analog clock animation or a progress bar, and if progress bar, customizing the accent color.`  - this could be done, but I prefer to have little code as possible so I don't plan to add that

`"...nah, I'll just keep going" should be a material button, with customizable text, with a default of "Skip" or "Skip Break"

A "Pause" button at the side of the skip break button, clicking it will show the Pause times context menu.

Settings page needs improvement. Layout, and material animated toggle button instead of checkbox.

Why are the texts lower case!?`  - there will be rework of the whole app soon, so all will change :D 

`Any reason why the logo in the tray is monochrome by default?` because of macOS guidelines

`Skip break with a keyboard shortcut` - Cmd/Ctrl+X 

`Language settings. The app's text can be modified in a JSON file.` do you mean translations? or break ideas?

**Comment by angelhdz** [comment]
### Hello there! 
Wow, didn't expect a detailed response. I appreciate your time and energy.

Thank your for all the information provided. By _"Language settings"_ yes I mean translations.

Have a nice day!

**Comment by kerwin15** [comment]
> `Custom times` - what specifically do you mean? You can edit interval and how long the breaks are

Not sure if it's the same idea but my suggestion would be a work hours interval. Typically, I only want the program to prompt me while I'm working.

Something like: 
![image](https://user-images.githubusercontent.com/941990/67711416-efc7d080-f98f-11e9-86d9-168b9b605fef.png)

**Comment by angelhdz** [comment]
@kerwin15 hey, thanks for replying! 

OMG! I can't believe I didn't notice the '+' sign to change the intervals!  I thought it was part of the text. Thank you for opening my eyes! So at least one of my suggestions is already possible.

About your idea, sounds great to me! Select timers according to weekdays.

**Comment by hovancik** [comment]
guys, there is PR to make + more obvious, maybe comment thee? #488

**Comment by angelhdz** [comment]
@hovancik , @kerwin15 was just replying to one of my Feature Requests, so it makes sense discussing it here.

**Comment by angelhdz** [comment]
@kerwin15 I love this suggestion. It's like EXPECTED and OBVIOUS that was missed when designing this screen's GUI...

https://user-images.githubusercontent.com/9328196/67353909-9a5f6f80-f508-11e9-8cc3-166fa9bce51e.png
