### ISSUE TITLE
Config.json modifications to disable specific break ideas are ignored

### ISSUE THREAD

**Issue by ketura** [hovancik/stretchly#487]
### Prerequisites

- [+] I'm using latest version: v0.21.0
- [+] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

I'm a fan of some of the break suggestions (specific stretches, eye focus, etc), and not a fan of others (don't tell me to smile, dammit, this scowl has a long and storied heritage).  So, I went into the config.json hosted in my AppData/Roaming folder with an aim to fix this (found by going into the about page, ctrl + D, and clicking the link).  

I edited config.json, first by deleting the offending entries, and later by restoring them and changing the offending entries from `"enabled": true` to `"enabled": false`.  Neither of these actions prevented the app from occasionally suggesting I stop glaring at the world.  I then went so far as the edit the text of the bad entries ("Take a moment to shake your fist at being alive") and restarting Stretchly, but it has had no effect.  

I've verified that the other entries in the config.json get read, specifically the time duration entries, but for some reason whatever code handles the break suggestions does not seem to get them from my config.

Operating system: Windows 10 Pro 1809

### Steps to Reproduce

1. Edit local user config.json
2. Remove an entry from either the `breakIdeas` or `microbreakIdeas` arrays, or change the `enabled` field to `false`, or alter the text in `data`.
3. Save the config
4. Restart Stretchly
5. Advance to the next break/microbreak a few times until the entry you altered shows up

**Expected behavior:** the break suggestion should or should not show up (or have the edited text) as reflected by the entry in the config

**Actual behavior:** the program insists on suggesting you smile no matter what you do

**Reproduces how often:** Always reproduces, but may take several microbreak advances to be evident

**Comment by ketura** [comment]
....oh.  Why on earth is there an additional setting to tell the program to read those settings?  I notice there's no `useBreakDurationFromSettings` entry buried in the list, for instance.  Seems inconsistent and unnecessarily tedious.

Still, that addresses my complaint, at least.  Thanks!

**Comment by hovancik** [comment]
It's because with new releases I often add new break ideas. If they were in settings, I would have to update settings everytime. It would be hard to find which to add, which were changed by user so I should not re-add them etc.. Or user would need to update file every time there are new breaks.   

So by default I have special file in app with default ideas (so with update people get new break ideas) and those in settings file are for advanced user. 

It is not perfect as well, because if you have installed very first version of stretchly and now try to have custom break ideas with latest version, settings file would only have break ideas from very first stretchly version (or whatever version you installed first).
