### ISSUE TITLE
extra microbreak happens 2 minutes after expected one

### ISSUE THREAD

**Issue by ludant** [hovancik/stretchly#511]
### Prerequisites

- [ X ] I'm using latest version: v 
- [ X ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

a microbreak is triggered about 2 minutes after which, a normal 20 minute interval is set.  for 5-minute breaks, a second 5-minute break is called 6 minutes later.

Operating system: Ubuntu 19.10

### Steps to Reproduce

(unsure)

**Expected behavior:** normal microbreak/break intervals

**Actual behavior:** a second microbreak occurs after 2 minutes, then has a normal 20-minute interval.  after 5-minute breaks, the app calls another break after 4-6 minutes.

**Reproduces how often:** unknown

**Comment by hovancik** [comment]
Hi @ludant 
Does this happen when you attempt to finish break early? Because what you describe looks like default behavior: when you finish break early (during first 30% of break), you only postpone it (for 2/5mins for micro/regular break). 

You can disable this behavior on first settings page by unchecking "allow to postpone"

**Comment by ludant** [comment]
that must be it.  i was a bit confused about what that box meant, clearly.  thanks!
