### ISSUE TITLE
"stretchly.app" would like to control this computer using accessibility features - ??

### ISSUE THREAD

**Issue by mehov** [hovancik/stretchly#527]
First and foremost, thanks for the great app!

### Prerequisites

- Version I'm using: v 0.21.1
- I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues): [yes](https://github.com/hovancik/stretchly/issues?utf8=%E2%9C%93&q=control+this+computer)

### Description

I got this prompt and I'm not sure what it means. If this is a feature I want, I'll happily grant the permission.

![prompt](https://i.imgur.com/9o5wBJc.png)

On the latest iOS Bluetooth permission prompts, the app developers have a chance to explain why they need it, and that makes it easier to decide whether you want to grant the permission. I'd hope Mac OS can do the same?

Operating system: Mac OS 10.14

### Steps to Reproduce

1. Have an existing app suggest you to update
2. Download the new .dmg from the official site
3. Install and launch it

**Expected behavior:** Provide a clear message explaining what is going on

**Actual behavior:** Generic Mac OS message

**Reproduces how often:** After every reinstall (e.g. upgrading)

**Comment by hovancik** [comment]
Interesting. Based on what I see here in https://github.com/electron/electron/issues/14837, it's probably because in Stretchly you can quit break early with `Cmd+X` shortcut. 

Not sure why it would start asking now, as it's there forever. 

I guess if you don't allow, you won't be able to use the shortcut. 

But in general: there is no piece of code that Stretchly has to work directly with `accessibility features` (whatever that means) so hard to say...

**Comment by hovancik** [comment]
As this is pretty old, closing. Not sure if I can help here.
