### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Temjeh** [hovancik/stretchly#595]
Hi and thank you

Since last uptdate, my Bitdefender reconize your soft like a virus!
You know why?

Claude

**Comment by hovancik** [comment]
Hi @Temjeh , if you downloaded from my website or this repository, you should be fine. 

Not sure why they would say it's a virus ;/ But many antivirus say it's virus at first because of Electron (the tech I use to build Stretchly) until a few users report it as false positive.

Never seen it after app update, though

**Comment by Temjeh** [comment]
Thank you.
Weird yet I did the update on the link directly from the program!

A+

**Comment by hovancik** [comment]
:+1:
