### ISSUE TITLE
Feature request: stereograms

### ISSUE THREAD

**Issue by vladkozlov69** [hovancik/stretchly#632]
Hello Jan,

First of all, Stretchy is amazing app!

can I suggest a new feature? The Stereograms is an amazing way for eye relaxation and trainings for eye accommodation muscles. The idea is to add a folder with stereogram pictures to app and randomly display them in the app window. during the  microbreaks.

**Comment by balazsnasz** [comment]
If @hovancik approves it, I could add a config.json parameter + a checkbox (on/off) to Contributor Preferences window to enable this feature. We need CC0 (or a licence which complies with Stretchly's open source licence) stereogram images though if we go ahead with this.

What do you think?

**Comment by hovancik** [comment]
Hi y'all, 

there are actually few issues related to the break screen: 
- no translations #310
- people wanna see images #160
- companies wanna use custom messages they control

That's why I would like to do something similar to what's described here: https://github.com/hovancik/stretchly/issues/310#issuecomment-557877850 + add option to have images. 

That would basically allow to use break window as platform where people could use their own repos as controllers to what they see in break windows... 

I will close this issue, but please subscribe to the other ones for updates.
