### ISSUE TITLE
Allow custom slider values in schedule preferences 

### ISSUE THREAD

**Issue by smcveigh941** [hovancik/stretchly#644]
### Prerequisites

- ✅ I'm using latest version: v1.0.0
- ✅ I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- ✅ I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

May I suggest a textbox to allow a user to input their own scheduled timeframe for breaks? I found the current implementation especially annoying for long breaks when I want to take a break every hour and a 1/2, but the closest I can set the schedule to is 75 minutes or 100 minutes. Someone may think this is trivial but it can be useful for someone who wishes to work in 90 minute (or other customisable timeframe) stints. 

Operating system: MacOS Catalina

### Steps to Reproduce

1. Preferences -> Schedule
2. Drag sliders for mini breaks and long breaks

**Expected behavior:**
I would like the timeframes to be more customisable, maybe with a small textbox. When a value is entered into the textbox, the slider can automatically adjust to an appropriate position. 

**Actual behavior:**
Slider positions are fixed and restrictive.

### Additional Information

Some validation required for the textbox. Also, when a value is entered, the slider could auto-adjust to an appropriate position. Maximum values may be required (e.g. maximum 105 seconds for mini break every maximum 65 minutes, and a similar rule for long breaks)

Please let me know what you think. I am willing to investigate and complete the work needing done once approved!

**Comment by hovancik** [comment]
Hi @smcveigh941 ,

regarding Mini Breaks: I plan to change it in a way, that there will be few values under 2 minutes and then bigger values like 3 , 5, 10, 15 minutes. Default value is quite small (20 seconds), so it looks confusing if I would have a seconds interval up to let's say 15 minutes.  (That's why I went with 105 seconds as end value)

regarding Long Breaks: there are times show, ie "Every 30 minutes", but in reality, it's "Show Long Break after X Mini Breaks." So for defaults, you have "Show Long Break after 2 Mini Breaks", 10+10+10 minutes.
