### ISSUE TITLE
What happened to Stretchly?

### ISSUE THREAD

**Issue by st4ycool** [hovancik/stretchly#716]
Why Collin Shanlei is using his own logo multiplied by 2 as a stretchly logo?
![image](https://user-images.githubusercontent.com/17159323/94784381-c05ae880-03d6-11eb-8fd2-e31fd8f9e749.png)
His next project will be his logo multiplied by 3? And then by 4? ) New logo everytime, very insteresting.

When I remember Stretchly it was very very well designed app. Menu was so good, it was so minimalistic and pristine. I was having so much pleasure using it.
![image](https://user-images.githubusercontent.com/17159323/94784189-7a9e2000-03d6-11eb-9e96-73fab1cca887.png)

And now I have THIS unfinished school project UI thing. 
![image](https://user-images.githubusercontent.com/17159323/94784200-7eca3d80-03d6-11eb-863c-af3eece23f08.png)

Sorry for the flame, I just don't understand this type of upgrades

P.S.
Can Collin draw a heart or not?
![image](https://user-images.githubusercontent.com/17159323/94784227-8984d280-03d6-11eb-8174-98ccb9e32156.png)

**Comment by hovancik** [comment]
Hi, 

I asked designers to help me with redesign of Stretchly because there were a lot of issues that I did not know how to solve them (https://github.com/hovancik/stretchly/issues/421). (I am not a desinger).

He was kind enough to help and did everything for free. 

I personally like the new style better, it's much better UX and UI. The same with logo, I tested with with many people and the most of them liked the new one. One could also argue that it is the same as ying-yang, so I do not worry whether it is similar to his own logo. 

I am very grateful about everything he had done.
