### ISSUE TITLE
Typo in German Translation 'Nicht stöhren' 

### ISSUE THREAD

**Issue by Whitedoteu** [hovancik/stretchly#751]
### Prerequisites

- [X] I'm using latest version: v <1.2.0>
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

There is an Typo in the de.json translation file.

Line 50:
     old :   "monitorDnd": "Pausen auch bei 'Nicht stöhren' anzeigen"
     new :  "monitorDnd": "Pausen auch bei 'Nicht stören' anzeigen",

**Comment by hovancik** [comment]
Hi @Whitedoteu , feel free to create PR for extra karma :)

**Comment by Whitedoteu** [comment]
Oh :)  I Hoped i don't have to do but maybe i have time on the Weekend :D

**Comment by hovancik** [comment]
Hi @Whitedoteu , you don't have to but I prefer people to do it because it's easy and you will get access to extra contributor preferences :) 

You can simply edit file online here: https://github.com/hovancik/stretchly/blob/master/app/locales/de.json and github will create PR for you :) 

Let me know if I should make the edits :)

**Comment by Whitedoteu** [comment]
WOW i didn't know that you can edit direktly over Github Webpage. 

Pull request is done. Thx for the help.
