### ISSUE TITLE
Global shortcuts

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#791]
Add Global shortcuts for: 
- [x] reset breaks
- [x] toggle between breaks/pause 
- [x] skip to mini
- [x] skip to long
- [x] skip to next

Do we need shortcuts to for Pause for 1/2/etc and till morning? 

Something else? 

How should those shortcuts look like? I am not really shortcut person but considering they are global, would be nice to find something not taken by other popular apps (if possible) , yet usable. 

https://www.electronjs.org/docs/tutorial/keyboard-shortcuts

**Comment by YMan84** [comment]
Something I would really really like is having a global shortcut for "Pause". 
I've had quite a few times where the break reminder would pop up on my screen when i'm showing  a coworker/manager something on my screen, or doing some sort of sharing. A global hotkeys with maybe some sort of notification showing me what state it's currently in (Maybe changing the toolbar icon color?) would be immensely helpful.

**Comment by hovancik** [comment]
I've added Pause/Resume shortcuts. Stretchly already changes icon when it's paused.

**Comment by AnKun2** [comment]
@hovancik Hi,

Instead of "skip to mini/long" break, I would like to suggest a shortcut "skip to next", where "next" is whatever break comes next. 

The reasoning is as follows:

Instead of getting a notification "Hey, the mini break is coming in 15 seconds, let's drop our current task and have a break for 20 seconds" I prefer working like this -- "Hey, it is time to have a break. Let's finish our current task, then you can press a global shortkey to initiate a break when you're ready".

For discipline, I set notification interval for 60 seconds, usually this time is enough to finish whatever task I'm focused on in the moment. But, I can finish it much faster than 60 seconds. Then, I would like to have a global shortcut to say "Hey, I have finished the current task, let's not wait the whole 60 seconds and initiate the break right now". And I don't have to think about whether I want to initiate a mini or long break, I just want whatever break comes next.

Hope it makes sense, and, I believe, many users could benefit from this workflow.

**Comment by saidelike** [comment]
I am aware of the 2 following shortcuts already available:

```json
{
    ...
	"endBreakShortcut": "CmdOrCtrl+X",      // Postpone/Finish Break Shortcut https://github.com/hovancik/stretchly#postponefinish-break-shortcut
	"pauseBreaksToggleShortcut": "",        // Toggling between Pause Breaks and running breaks https://github.com/hovancik/stretchly#toggle-breaks-shortcut
```

I would be nice to have a way to define shortcuts for the following options:

- skipToNextMiniBreakShortcut
- skiptoLongMiniBreakShortcut
- resetBreakShortcut

That would be particularly useful for **accessibility reasons**.

Even if the shortcuts are not defined and left for the users to be defined, that would be great. Otherwise I can suggest:

- skipToNextMiniBreakShortcut: "CmdOrCtrl+F18"
- skiptoLongMiniBreakShortcut: "CmdOrCtrl+F19"
- resetBreakShortcut: "CmdOrCtrl+F20"

**Comment by hovancik** [comment]
I'm adding more shortcuts in #1362
