### ISSUE TITLE
Short freezes of online video in browsers when the program is running

### ISSUE THREAD

**Issue by sakralbar** [hovancik/stretchly#804]
### Description
When watching an online video in a browser (Chrome, Firefox), there are short freezes of the picture, about once every 5-6 seconds. If you close Stretchly, then the hangs disappear.

Operating system:
Ubuntu 20.04 

### Steps to Reproduce

Run Stretchly
Play online video in any browser

**Expected behavior:** [What you expect to happen]
No short-term delays in video playback

**Actual behavior:** [What actually happens]
Short-term periodic picture delays during video playback

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by hovancik** [comment]
Hi, is it during Break or also outside of break?

**Comment by sakralbar** [comment]
Yes, it's also outside of break, when program is just running. My video card is amd rx460 if it matters.

**Comment by hovancik** [comment]
Well, no idea. I'll be releasing new version hopefully soon with new Electron version so let's see if that helps.

**Comment by sakralbar** [comment]
I have tested playing the same video on version 1.4 and it looks like the problem is no longer being observed.

**Comment by AlexMKX** [comment]
Same here.
Chrome browser is freezing after the break window is closed.
Steps to reproduce : 
1. Open chrome as foreground window.
2. Start the break manually.
3. Close the break window.
4. Chrome window become unresponsible after the break window is closed.

To recover chrome window - switch the chrome tab to another and switch it back afterwards.

It seem the problem is caused surface update process. After chrome updates the surface - everything is working OK.
Probably something like invalidate_rect message sent to foreground window, will solve the issue.
