### ISSUE TITLE
Bug fix: Resuming after *pause*

### ISSUE THREAD

**Issue by r3a1d3a1** [hovancik/stretchly#813]
Currently, pausing breaks resets all the timers and counters.
As one may expect from the word "Pause", it'd be better to keep them as they were after the pause period is over.

**Comment by armudgal** [comment]
Hey @hovancik. What is your take on this? If this is free to take, I would like to work on it. Said that, if you think I should start with some other issue please do let me know. 
Thanks :D

**Comment by hovancik** [comment]
Hi @armudgal , this is free to take, but it requires some thinking. Stretchly does not have any "state" and I am pretty much sending a lot of events up and down. And it's all connected(with DND, idle time and such). 

Here are some related cards: https://github.com/hovancik/stretchly/issues/503, https://github.com/hovancik/stretchly/issues/772

Feel free to take a look at the code and write here how would you solve it?

**Comment by Rose-Haile** [comment]
Wouldn't it be better if you were prompted to take a break immediately after the pause? Or at least if the countdown continues running while paused but once it reaches zero it's paused there? I imagine that if you're using a productivity app and don't want to be interrupted and spend a significant amount of time using it, that after you're done would be a good time to take a break. In my use case (after zoom meetings) I'd like a break reminder then instead of 15 minutes later.

**Comment by hovancik** [comment]
Well, I guess depends how you use pause, whether it means you take your own break, or it's a time when you don't wanna be disturbed.

**Comment by hovancik** [comment]
closing in favor of #1248
