### ISSUE TITLE
Feature: Show Postpone Shortcut in Notification

### ISSUE THREAD

**Issue by Welldoor** [hovancik/stretchly#825]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

1. How to postpone a break smoothly?
2. Just read in github, there is actually a shortcut for this.
3. Letting users know there is a shortcut! -> Make it simple: Add current Shortcut information to the notification window.

**Edit:** Maybe there was a misunderstanding. Thought I could skip the pause already when a notification is showing up..?!

**Comment by hovancik** [comment]
Hi @Welldoor , you can postpone/skip only when break is on: if you hover over links to postpone/skip, shortcut is shown

**Comment by justauserid** [comment]
@Welldoor that will defeat a lot of purpose of this app. Besides, as stated in last comment this is already possible.

**Comment by hovancik** [comment]
Yep, I agree with @justauserid : I am trying to subtly make people take a break :) It is possible to assign action to click on notification, but if I would assign "skip" to it, many people would simply skip all the time, and often by accident.

**Comment by EvanGoss** [comment]
Perhaps this could be a user preference setting?  I was using https://breaktimer.app but switched the Stretchly for the ability to pause breaks for 1 hr.  I use that feature when I'm in a meeting. If I forget to pause breaks, I'd rather be able to skip breaks before they actually start by clicking "skip" or "postpone" on the notification. Otherwise, the app is great for me.

**Comment by hovancik** [comment]
With the system notifications that I use, there is no cross-platform way to add buttons.
