### ISSUE TITLE
M1 Mac build?

### ISSUE THREAD

**Issue by jasonbronson** [hovancik/stretchly#837]
do you have a release for electron 11 for M1 macs?
https://www.electronjs.org/blog/electron-11-0

**Comment by hovancik** [comment]
@jasonbronson does the current dmg works for you on M1?

**Comment by jasonbronson** [comment]
@hovancik it runs fine but it's showing as intel so not compiled for ARM M1 macs. 
https://jmp.sh/wIuNT3B

**Comment by blimmer** [comment]
@hovancik , the current app does work on M1 macs, but it's quite slow and requires [Rosetta](https://support.apple.com/en-us/HT211861) to be installed. It'd be great if an ARM-native version were published, as well 👍

**Comment by hovancik** [comment]
Hey sorry to hear that ;/ I don't have M1 mac unfortunately and I build on CI with electron-builder. If I read this correctly, it does not support m1, yet: https://github.com/electron-userland/electron-builder/issues/5850

many more issues opened about M1: https://github.com/electron-userland/electron-builder/search?q=M1&type=issues

**Comment by jasonbronson** [comment]
@hovancik https://www.electronjs.org/blog/electron-11-0#highlight-features shows it's available in ver 11

**Comment by hovancik** [comment]
yep, but I mean `electron-builder`, which I use to make packages

**Comment by blimmer** [comment]
Would it be possible to re-open this issue and we can keep an eye on the `electron-builder` project as those issues progress? I can subscribe to a few of them.

**Comment by blimmer** [comment]
I had a bit more time today to look into this. I believe we can build an M1-targetted DMG using the current setup. I have this working on my fork - you can find an M1 version on the [1.9.0-beta.1 GitHub release](https://github.com/blimmer/stretchly/releases).

<img width="1169" alt="Screen_Shot_2022-02-19_at_18_05_13" src="https://user-images.githubusercontent.com/630449/154824428-3a3e18b2-a76f-4ed1-bde7-da55adc5e7f0.png">

I did encounter the issue specified in the Electron Builder issue linked above (https://github.com/electron-userland/electron-builder/issues/5850). When you drag the M1 version of Stretchly to `Applications` and try to open it, you get this error message:

<img width="260" alt="Screen Shot 2022-02-19 at 18 06 23" src="https://user-images.githubusercontent.com/630449/154824445-08706387-9104-4c94-a376-0e0e44d9a184.png">

However, as mentioned on the electron-builder issue, this isn't a problem with electron, electron-builder, or GitHub actions. Starting with MacOS Big Sur, Apple requires all executables to be signed on Apple Silicon machines (see [this comment](https://github.com/electron-userland/electron-builder/issues/5850#issuecomment-992302142)).

So, because the application isn't signed, you have to manually override this warning like this:

```
> sudo xattr -r -d com.apple.quarantine /Applications/Stretchly.app
```

Then the M1 version of Stretchly works!

<img width="960" alt="Screen_Shot_2022-02-19_at_18_08_31" src="https://user-images.githubusercontent.com/630449/154824487-99a6fa2a-d90e-4a60-9d28-7215edd15c59.png">

I opened https://github.com/hovancik/stretchly/pull/1099 to support this.

**Comment by blimmer** [comment]
Homebrew cask update PR is here: https://github.com/Homebrew/homebrew-cask/pull/119568
