### ISSUE TITLE
Feature: Schedule "Go to sleep" reminder

### ISSUE THREAD

**Issue by mat-b-** [hovancik/stretchly#841]
It would be great if Stretchly could remind about going to sleep at a specifed time

**Comment by mwoz123** [comment]
somehow similar to #667

**Comment by mat-b-** [comment]
> somehow similar to #667

It's a different use case:
Imagine starting session after coming home at 9 P.M.
Stretchly could display "Go to sleep" reminder at 10 P.M, even if daily clock limit from #667 is set to longer than 1 hour.

If the goal of the app is to take breaks, it can be seen as taking a long, 8-hours sleeping break ;)

**Comment by hovancik** [comment]
Hey, so with a lot of similar requests (to basically add different custom reminders at different times and intervals etc), I decided to hack a app for that: https://github.com/hovancik/later-on 

It's very alpha and has no fancy UI, only config file to edit, but it's a start. 

I created another app because I want to keep Stretchly to be "The break time reminder app". Having too many features would make it hard to understand and use for new people. 

Feel free to try LaterOn :)
