### ISSUE TITLE
Can't interact with the screen after the full screen break ends

### ISSUE THREAD

**Issue by aliwayne** [hovancik/stretchly#882]
Hi there,

After the break ends and I've set it in full screen, the screen seems freeze even videos look like paused but the audio is still playing! the screen get back to normal after I click the right mouse button or use Alt+Tab.

**Comment by hovancik** [comment]
@aliwayne please provide the information from the bug report template

**Comment by cyniphile** [comment]
### Prerequisites

- [x ] I'm using latest version: v Versione corrente 1.4.0
- [ x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [ x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

After fullscreen break, Chrome becomes visually (but not functionally) unresponsive until I alt-tab or open a new tab.  For example, just after a break if I type something, nothing with show up, but once I've alt-tabed, the characters I type are now visible

Operating system: Windows 10 enterprise 20H2 19042.804

### Steps to Reproduce

1. open chrome
2. wait for fullscreen break
3. After break completes, try type, scroll or otherwise interact with the existing chrome window

**Expected behavior:** typing etc works

**Actual behavior:** no visual updates until after an alt-tab or new tab

**Reproduces how often:** Always

### Debug information

Nothing odd in logs

{
    "microbreakDuration": 20000,
    "microbreakInterval": 1200000,
    "breakDuration": 300000,
    "breakInterval": 2,
    "breakNotification": true,
    "microbreakNotification": true,
    "breakNotificationInterval": 30000,
    "microbreakNotificationInterval": 10000,
    "microbreak": true,
    "break": false,
    "microbreakStrictMode": false,
    "breakStrictMode": false,
    "morningHour": 6,
    "microbreakPostpone": true,
    "breakPostpone": true,
    "microbreakPostponeTime": 120000,
    "breakPostponeTime": 300000,
    "microbreakPostponesLimit": 1,
    "microbreakPostponableDurationPercent": 30,
    "breakPostponesLimit": 1,
    "breakPostponableDurationPercent": 30,
    "mainColor": "#478484",
    "transparentMode": false,
    "opacity": 0.9,
    "audio": "wind-chime",
    "volume": 1,
    "fullscreen": true,
    "ideas": true,
    "naturalBreaks": true,
    "naturalBreaksInactivityResetTime": 300000,
    "allScreens": true,
    "useIdeasFromSettings": false,
    "language": "it",
    "notifyNewVersion": true,
    "isFirstRun": false,
    "posLatitude": 0,
    "posLongitude": 0,
    "useMonochromeTrayIcon": false,
    "useMonochromeInvertedTrayIcon": false,
    "silentNotifications": false,
    "monitorDnd": false,
    "microbreakStartSoundPlaying": false,
    "breakStartSoundPlaying": false,
    "themeSource": "system",
    "endBreakShortcut": "CmdOrCtrl+X",
    "breakWindowWidth": 0.85,
    "breakWindowHeight": 0.85,
    "checkNewVersion": true,

**Comment by aliwayne** [comment]
What I did, is just switch to window mode instead of full-screen mode and the problem no longer exists.

Hope the problem fixed because full-screen is better.

Regards,
Ali

**Comment by hovancik** [comment]
This is a chrome issue, looks like. Can you try the solution mentioned here: https://github.com/hovancik/stretchly/issues/783#issuecomment-762819646

**Comment by ztrhgf** [comment]
I had same problem and setting chrome flag what @hovancik mentioned helped!

**Comment by jt007** [comment]
Have same problem.
Problem occurs when break setting is "full screen". When breaks setting is "window", it works fine. 

By tapping another tab, and then go back to the previous tab, scrolling works again. Need to do this procedure after every single mini break.

Version: 1.4.0 (offline installer)
System: windows 10, 64 bit. 16gb ram. Chrome browser. Windows update and Chrome is both latest version.

Edge and Firefox seems to work, but not Chrome as I use.
Problem exist either with or without external monitor.
I am not sure if I want to alter the default chrome settings which could give more workload on the system.

Since the problem happens only in "full screen" setting, and not in "window" setting, perhaps it could be a possible workaround to add an option in settings for "full screen (Chrome users)", which is just almost full screen. Perhaps that will not trigger the freeze for all Chrome users.

Do you think that could be a solution to the problem @hovancik ?

**Comment by hovancik** [comment]
@jt007 you can use Windowed mode and specify 99% or sth: https://github.com/hovancik/stretchly#break-window-size-
