### ISSUE TITLE
[Feature request]: Add systemd user unit so application can auto start on linux

### ISSUE THREAD

**Issue by unquote7083** [hovancik/stretchly#984]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

all systemd-based

### Problem description

No systemd unit means users will need to create their own, or use other means, or have no auto start functionality on linux.

### Possible solution

Add systemd user unit so application can auto start on linux

### Alternative solutions

XDG Autostart might be an alternative

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I am using `electron-builder` to make builds. Let's try to find if it can somehow do it. 

In general, I am using https://www.electronjs.org/docs/api/app#appgetloginitemsettingsoptions-macos-windows and there is also an item in Preferences, but this supports only Windows and Mac so it is hidden in Linux. 

I would prefer to have solution that support more general linux approaches, not only systemd. There might be some library that does that. So that we can then also enable "Start at login" option for Linux.

**Comment by hovancik** [comment]
This seems to be maintained but would be good to spend more time looking at different options: https://github.com/Izurii/easy-auto-launch

**Comment by unquote7083** [comment]
Thanks. I think either way it would be beneficial to have the systemd unit file included, as it does nothing on its own, doesn't need any sort of regular updates, and is a very small file.

**Comment by nihil-admirari** [comment]
`systemd` unit starts regardless of whether GUI is available or not.

> XDG Autostart might be an alternative

Starts only when desktop environment is running.

**Comment by hovancik** [comment]
closed in #990 

won't get distributed in app, as I could not find how it works with electron-builder, but people can check it in repo
